// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class MobileToMediaPlaneLogoutRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MobileToMediaPlaneLogoutRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMobileToMediaPlaneLogoutRequest(bb:flatbuffers.ByteBuffer, obj?:MobileToMediaPlaneLogoutRequest):MobileToMediaPlaneLogoutRequest {
  return (obj || new MobileToMediaPlaneLogoutRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMobileToMediaPlaneLogoutRequest(bb:flatbuffers.ByteBuffer, obj?:MobileToMediaPlaneLogoutRequest):MobileToMediaPlaneLogoutRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MobileToMediaPlaneLogoutRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startMobileToMediaPlaneLogoutRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addSessionId(builder:flatbuffers.Builder, sessionId:number) {
  builder.addFieldInt32(0, sessionId, 0);
}

static endMobileToMediaPlaneLogoutRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMobileToMediaPlaneLogoutRequest(builder:flatbuffers.Builder, sessionId:number):flatbuffers.Offset {
  MobileToMediaPlaneLogoutRequest.startMobileToMediaPlaneLogoutRequest(builder);
  MobileToMediaPlaneLogoutRequest.addSessionId(builder, sessionId);
  return MobileToMediaPlaneLogoutRequest.endMobileToMediaPlaneLogoutRequest(builder);
}
}
