// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class MobileToMediaPlaneLoginRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MobileToMediaPlaneLoginRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMobileToMediaPlaneLoginRequest(bb:flatbuffers.ByteBuffer, obj?:MobileToMediaPlaneLoginRequest):MobileToMediaPlaneLoginRequest {
  return (obj || new MobileToMediaPlaneLoginRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMobileToMediaPlaneLoginRequest(bb:flatbuffers.ByteBuffer, obj?:MobileToMediaPlaneLoginRequest):MobileToMediaPlaneLoginRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MobileToMediaPlaneLoginRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startMobileToMediaPlaneLoginRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addSessionId(builder:flatbuffers.Builder, sessionId:number) {
  builder.addFieldInt32(0, sessionId, 0);
}

static endMobileToMediaPlaneLoginRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMobileToMediaPlaneLoginRequest(builder:flatbuffers.Builder, sessionId:number):flatbuffers.Offset {
  MobileToMediaPlaneLoginRequest.startMobileToMediaPlaneLoginRequest(builder);
  MobileToMediaPlaneLoginRequest.addSessionId(builder, sessionId);
  return MobileToMediaPlaneLoginRequest.endMobileToMediaPlaneLoginRequest(builder);
}
}
