// automatically generated by the FlatBuffers compiler, do not modify

export enum PhaseEnums {
  Min = 0,
  None = 1,
  Intro = 2,
  IntroCountdown = 3,
  Tutorial = 4,
  WarpVote = 5,
  AsteroidWaveOne = 6,
  AsteroidWaveOneLeaderboard = 7,
  AsteroidWaveTwo = 8,
  AsteroidWaveTwoLeaderboard = 9,
  AsteroidWaveThree = 10,
  AsteroidWaveThreeLeaderboard = 11,
  SaveTheShip = 12,
  FinalLeaderboard = 13,
  Outro = 14,
  Max = 15
}
