"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.PhaseEnums = void 0;
var PhaseEnums;
(function (PhaseEnums) {
    PhaseEnums[PhaseEnums["Min"] = 0] = "Min";
    PhaseEnums[PhaseEnums["None"] = 1] = "None";
    PhaseEnums[PhaseEnums["Intro"] = 2] = "Intro";
    PhaseEnums[PhaseEnums["IntroCountdown"] = 3] = "IntroCountdown";
    PhaseEnums[PhaseEnums["Tutorial"] = 4] = "Tutorial";
    PhaseEnums[PhaseEnums["WarpVote"] = 5] = "WarpVote";
    PhaseEnums[PhaseEnums["AsteroidWaveOne"] = 6] = "AsteroidWaveOne";
    PhaseEnums[PhaseEnums["AsteroidWaveOneLeaderboard"] = 7] = "AsteroidWaveOneLeaderboard";
    PhaseEnums[PhaseEnums["AsteroidWaveTwo"] = 8] = "AsteroidWaveTwo";
    PhaseEnums[PhaseEnums["AsteroidWaveTwoLeaderboard"] = 9] = "AsteroidWaveTwoLeaderboard";
    PhaseEnums[PhaseEnums["AsteroidWaveThree"] = 10] = "AsteroidWaveThree";
    PhaseEnums[PhaseEnums["AsteroidWaveThreeLeaderboard"] = 11] = "AsteroidWaveThreeLeaderboard";
    PhaseEnums[PhaseEnums["SaveTheShip"] = 12] = "SaveTheShip";
    PhaseEnums[PhaseEnums["FinalLeaderboard"] = 13] = "FinalLeaderboard";
    PhaseEnums[PhaseEnums["Outro"] = 14] = "Outro";
    PhaseEnums[PhaseEnums["Max"] = 15] = "Max";
})(PhaseEnums || (exports.PhaseEnums = PhaseEnums = {}));
//# sourceMappingURL=phase-enums.js.map