// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class RepeaterLoginRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RepeaterLoginRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRepeaterLoginRequest(bb:flatbuffers.ByteBuffer, obj?:RepeaterLoginRequest):RepeaterLoginRequest {
  return (obj || new RepeaterLoginRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRepeaterLoginRequest(bb:flatbuffers.ByteBuffer, obj?:RepeaterLoginRequest):RepeaterLoginRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RepeaterLoginRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startRepeaterLoginRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addSessionId(builder:flatbuffers.Builder, sessionId:number) {
  builder.addFieldInt32(0, sessionId, 0);
}

static endRepeaterLoginRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRepeaterLoginRequest(builder:flatbuffers.Builder, sessionId:number):flatbuffers.Offset {
  RepeaterLoginRequest.startRepeaterLoginRequest(builder);
  RepeaterLoginRequest.addSessionId(builder, sessionId);
  return RepeaterLoginRequest.endRepeaterLoginRequest(builder);
}
}
