// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class ShapeRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ShapeRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsShapeRequest(bb:flatbuffers.ByteBuffer, obj?:ShapeRequest):ShapeRequest {
  return (obj || new ShapeRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsShapeRequest(bb:flatbuffers.ByteBuffer, obj?:ShapeRequest):ShapeRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ShapeRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

shapeId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startShapeRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSessionId(builder:flatbuffers.Builder, sessionId:number) {
  builder.addFieldInt32(0, sessionId, 0);
}

static addShapeId(builder:flatbuffers.Builder, shapeId:number) {
  builder.addFieldInt32(1, shapeId, 0);
}

static endShapeRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createShapeRequest(builder:flatbuffers.Builder, sessionId:number, shapeId:number):flatbuffers.Offset {
  ShapeRequest.startShapeRequest(builder);
  ShapeRequest.addSessionId(builder, sessionId);
  ShapeRequest.addShapeId(builder, shapeId);
  return ShapeRequest.endShapeRequest(builder);
}
}
