// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class WebClientLoginRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WebClientLoginRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWebClientLoginRequest(bb:flatbuffers.ByteBuffer, obj?:WebClientLoginRequest):WebClientLoginRequest {
  return (obj || new WebClientLoginRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWebClientLoginRequest(bb:flatbuffers.ByteBuffer, obj?:WebClientLoginRequest):WebClientLoginRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WebClientLoginRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

repeaterSessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

pendingId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startWebClientLoginRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addRepeaterSessionId(builder:flatbuffers.Builder, repeaterSessionId:number) {
  builder.addFieldInt32(0, repeaterSessionId, 0);
}

static addPendingId(builder:flatbuffers.Builder, pendingId:number) {
  builder.addFieldInt32(1, pendingId, 0);
}

static endWebClientLoginRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createWebClientLoginRequest(builder:flatbuffers.Builder, repeaterSessionId:number, pendingId:number):flatbuffers.Offset {
  WebClientLoginRequest.startWebClientLoginRequest(builder);
  WebClientLoginRequest.addRepeaterSessionId(builder, repeaterSessionId);
  WebClientLoginRequest.addPendingId(builder, pendingId);
  return WebClientLoginRequest.endWebClientLoginRequest(builder);
}
}
